### ISSUE TITLE
Take into accout call ABI

### ISSUE THREAD

**Issue by RalfJung** [RalfJung/minirust#2]
Right now, our function calls ignore call ABI concerns. However, I think that should be fairly easy to fix (and this is similar to what Miri does): we define a type that contains "everything there is to know about how an argument is passed to the callee" (corresponding roughly to [`ArgAbi` in rustc](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/abi/call/struct.ArgAbi.html) but without the things that do not affect argument passing, like "read only" attributes). `Function::args` becomes a `List<(LocalName, ArgAbi)>`, and similar for `Terminator::Call::arguments`. When evaluating the `Call` terminator, we check that the ABIs all match up; if they do not, that is UB.

@digama0 you mentioned lack of support for call ABIs as a concern on Zulip; that probably was just a random example but I still wonder if you see any issue with this plan.

**Comment by bjorn3** [comment]
All `ArgAttributes` except `InReg` only add UB and can thus be ignored. `InReg` is only relevant on some targets I believe. LLVM documentation:

> This indicates that this parameter or return value should be treated in a special target-dependent fashion while emitting code for a function call or return (usually, by putting it in a register as opposed to memory, though some targets use it to distinguish between two different kinds of registers). Use of this attribute is target-specific.

**Comment by RalfJung** [comment]
[Here is what Miri currently does](https://github.com/rust-lang/rust/blob/09b0936db2bb3be67451c6f8948e90987e764f81/compiler/rustc_const_eval/src/interpret/terminator.rs#L178). For attributes it indeed only cares about `InReg`. I would hope to make this just `caller_mode == callee_mode` by removing things from the type that should not be relevant.

**Comment by RalfJung** [comment]
For the type comparison, I would hope that "size and align are equal" is good enough? Miri currently is stricter than that, except on `ScalarPair` where it is happy if the primitive types are the same... but can't `ScalarPair` types have extra padding? In https://github.com/rust-lang/rust/pull/96872 I think I got errors when I enforced that their sizes is just large enough to fit the two fields.

**Comment by bjorn3** [comment]
> but can't ScalarPair types have extra padding?

Not sure.

**Comment by RalfJung** [comment]
https://github.com/RalfJung/minirust/commit/4f151ab0459c6d8b731d93397d7dc31227554c0f at least helps here by making it UB if the size or alignment of caller and callee does not match. That should be enough for stack passing. To also cover register passing, we need the `ArgAbi`.
