### ISSUE TITLE
Resolve "destructive load", refactor argument passing

### ISSUE THREAD

**Issue by RalfJung** [RalfJung/minirust#85]
MiniRust currently has "destructive load" value expressions that fill the place with `Uninit` after loading the value from it. This is meant to model the `Move` operands from rustc. However this is quite unsatisfying since it means value expression evaluation can no longer be freely reordered. I'd like to find a better way to model this.

Following [this comment](https://github.com/rust-lang/unsafe-code-guidelines/issues/188#issuecomment-1372231841), we could have two kinds of assignment statements: a regular one, and a "move assignment" that has a place expression for the right-hand side and fills it with poison after being done. The question then becomes, what to do about function calls?

Currently argument passing (and return value handling) for function calls basically duplicates what assignments do. That is unsatisfying. Maybe there is a way to reuse the regular assignment statements...

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/issues/71117 has discussed argument passing and `move` a bit.

But what I meant above is that I'd like to restructure the language so that we don't need all of this

https://github.com/RalfJung/minirust/blob/7f7a3e89380a8cb318780cfb14ea5c76272e5e1f/lang/step.md?plain=1#L399-L418

**Comment by JakobDegen** [comment]
> However this is quite unsatisfying since it means value expression evaluation can no longer be freely reordered. I'd like to find a better way to model this.

Can you clarify here - are you concerned with this from the perspective of the semantics of Rust or Mir? In other words, would your concerns be resolved if we had a way to retain the same Rust semantics (and the same amount of UB) but had a less "disruptive" representation of this in our IR?

**Comment by RalfJung** [comment]
> would your concerns be resolved if we had a way to retain the same Rust semantics (and the same amount of UB) but had a less "disruptive" representation of this in our IR?

That would help a lot, yes. I am mostly concerned about this from a MIR/MiniRust perspective. I am worried that making (place and value) expression evaluation not reorderable could be a big mistake.

**Comment by RalfJung** [comment]
See [here](https://github.com/rust-lang/rust/issues/71117#issuecomment-1590570738) for another sketch of what `move` could mean in function calls.

I do not have a good idea for what it could mean elsewhere.

**Comment by RalfJung** [comment]
https://github.com/RalfJung/minirust/pull/135 removes destructive loads. I plan to add by-move argument passing in a style similar to https://github.com/rust-lang/rust/pull/113569.
